timezone: America/New_York
markdown: kramdown
permalink: /:year/:month/:day/:title
exclude:
- Gemfile
- Gemfile.lock
- README.md
- tidy.conf
- config.ru
- tasks
- bin
- public
- tmp
host: compasscontracting.com
assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache: _cache/assets
