markdown: redcarpet2
permalink: /:year/:month/:day/:title
pygments: false
exclude:
- Gemfile
- Gemfile.lock
- README.md
- tidy.conf
- config.ru
- tasks
- bin
- public
- tmp
host: compasscontracting.com
