#!/usr/bin/env zsh

# Create the site and tidy it.

env RM_STAR_SILENT=true rm -rf _site && mkdir _site && \
  bundle exec sass --scss --style compressed _sass/site.scss:resource/site.css && \
  bundle exec jekyll && \
  find _site -name "*.html" -exec tidy -config $(pwd)/tidy.conf {} \;
