#!/usr/bin/env zsh

# Create the site and tidy it.

env RM_STAR_SILENT=true rm -rf _site && mkdir _site && \
  compass compile --sass-dir _sass --css-dir resource && \
  jekyll && \
  find _site -name "*.html" -exec tidy -config $(pwd)/tidy.conf {} \;
